plugins {
    id 'java-library'
    alias(libs.plugins.spring.boot)
    alias(libs.plugins.spring.dependency.management)
}

dependencies {
    implementation project(':module-repository')
    annotationProcessor libs.mapstruct.processor
    implementation libs.mapstruct
    implementation libs.aspectjrt
    implementation libs.aspectjweaver
    implementation libs.spring.context
    implementation libs.spring.tx
    implementation libs.jsoup
    implementation libs.slf4j.api
}