CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS news_embeddings
(
    id          BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    news_id     BIGINT      NOT NULL UNIQUE,
    embedding   vector(768),
    embedded_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_news_embeddings_news FOREIGN KEY (news_id) REFERENCES news (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_news_embeddings_hnsw
    ON news_embeddings USING hnsw (embedding vector_cosine_ops)
    WITH (m=16, ef_construction=64);

CREATE TABLE IF NOT EXISTS chat_messages (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    session_id VARCHAR(64) NOT NULL,
    role VARCHAR(16) NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_chat_messages_session ON chat_messages (session_id,created_at);



