plugins {
    id 'java-library'
    alias(libs.plugins.spring.boot)
    alias(libs.plugins.spring.dependency.management)
}

dependencies {
    implementation project(':module-service')
    implementation libs.spring.boot.starter
    implementation libs.spring.boot.starter.web
    implementation libs.spring.boot.starter.data.jpa
    implementation libs.jackson.databind
}

bootJar {
    enabled = true
    archiveFileName = "fwaltnews.jar"
}

jar {
    enabled = false
}