plugins {
    id 'java-library'
    alias(libs.plugins.flyway)
    alias(libs.plugins.spring.boot)
    alias(libs.plugins.spring.dependency.management)
}

dependencies {
    implementation libs.flyway.core
    implementation libs.flyway.database.postgresql
    implementation libs.postgresql
    implementation libs.hibernate.vector
}