spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.flyway.enabled=true
spring.flyway.url=${SPRING_DATASOURCE_URL}
spring.flyway.user=${DB_USERNAME}
spring.flyway.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate

newsdata.api.redirect-url=https://fwaltnews.com/v1/news
cors.allowed-origins=https://fwaltnews.com
spring.security.oauth2.client.registration.github.redirect-uri=https://fwaltnews.com/login/oauth2/code/github
spring.security.oauth2.client.registration.google.redirect-uri=https://fwaltnews.com/login/oauth2/code/google
